using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MassUpdateApp.Core.Entities;

/// <summary>
/// Represents a single, validated request for a Purchase Order update,
/// intended to be persisted in the application's database.
/// </summary>
public class PurchaseOrderUpdateRequestEntity
{
    /// <summary>
    /// Primary key, generated by the database.
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// The Purchase Order number being updated.
    /// </summary>
    [Required]
    [MaxLength(10)]
    public required string PurchaseOrder { get; set; }

    /// <summary>
    /// The line number of the Purchase Order.
    /// </summary>
    [Required]
    public required int LineNumber { get; set; }

    /// <summary>
    /// The sequence number of the Purchase Order line.
    /// </summary>
    [Required]
    public required int Sequence { get; set; }

    /// <summary>
    /// The new date to be set for the Purchase Order line.
    /// </summary>
    [Required]
    [Column(TypeName = "date")]
    public required DateTime ReceiptDate { get; set; }

    /// <summary>
    /// The type of the date update (e.g., Confirmed, Changed).
    /// </summary>
    [Required]
    public required string DateType { get; set; }

    /// <summary>
    /// The ID of the user who initiated the update.
    /// </summary>
    [Required]
    public required string UserId { get; set; }

    /// <summary>
    /// The timestamp when the record was added to the database. Set automatically.
    /// </summary>
    public DateTime AddedDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// A flag indicating if this request has been processed and sent to the ERP system.
    /// </summary>
    public bool IsProcessed { get; set; } = false;

    /// <summary>
    /// The timestamp when the request was processed. Can be null if not yet processed.
    /// </summary>
    [Column(TypeName = "date")]
    public DateTime? ProcessedDate { get; set; }
}
